---
title: Neo4j Graph Model
---

flowchart LR
    VENDOR((Vendor))
    REPOSITORY((Repository))
    WORKFLOW((Workflow))
    COMMIT((Commit))
    COMPONENT((Component))
    VERSION((Version))
    %% VUNLNERABILITY((Vulnerability))

    VENDOR -->|OWNS| REPOSITORY
    VENDOR -->|PUBLISHES| COMPONENT
    REPOSITORY -->|CONTAINS| WORKFLOW
    WORKFLOW -->|PUSHES| COMMIT
    COMPONENT -->|DEPLOYS| VERSION
    VERSION -->|PUSHES| COMMIT
    %% COMMIT -->|HAS| VUNLNERABILITY
    
    C1((Workflow<br>Commit))
    C2((Workflow/Version<br>Commit or Version))
    C3((Workflow<br>Commit 1))
    C4((Workflow<br>Commit 2))

    C1 -->|USES| C2
    C3 -->|CHANGED_TO| C4
