---
title: Deployment View
---

flowchart-elk LR
    subgraph back [Backend]
        Crawler("Crawler")
        Gawd("GAWD")

        subgraph extract [Extractor]
            MExtractor("Extractor <br> Middleman")
            WExtractor("Workflow <br> Extractor")
            AExtractor("Action <br> Extractor") 
        end
    end

    subgraph db [Database]
        Neo@{shape: cyl, label: "Neo4j Instance"}
        Mongo@{shape: cyl, label: "MongoDB Instance"}
    end

    Crawler --- MExtractor
    MExtractor --- Neo
    MExtractor --- Mongo
    MExtractor --- WExtractor
    MExtractor --- AExtractor
    WExtractor --- Gawd
